---
- name: Create symbolic link for Snap
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure /snap is a symbolic link to /var/lib/snapd/snap
      ansible.builtin.file:
        src: /var/lib/snapd/snap
        dest: /snap
        state: link

